[package]
name = "rust-tdd-rest-api"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.1"
mockall = "0.13.1"
tokio = { version = "1.47.1", features = ["full"] }
uuid = { version = "1.18.1", features = ["v4"] }
