name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Add Clippy and Rustfmt components
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Run Rustfmt formatter
        run: cargo fmt -- --check

      - name: Run Clippy linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check compilation
        run: cargo check --all-targets --all-features

      - name: Build project
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Upload compiled Rust binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-tdd-rest-api-0.1.0
          path: target/release/rust-tdd-rest-api
